version: '3.8'
services:
    node:
        container_name: node-app
        build:
            context: ./files
            dockerfile: ./../Dockerfile
        depends_on:
            - db
        volumes:
            - ./files:/usr/src/app
        ports:
            - 80:80
    db:
        container_name: node-db
        image: mariadb:10.5.17
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: user
            MARIADB_PASSWORD: mypass
        ports:
            - "9906:3306"